# Generated by Django 4.2.1 on 2023-05-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_peb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='miniature',
            field=models.ImageField(upload_to=''),
        ),
    ]
