# Generated by Django 4.2.1 on 2023-05-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_peb', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.CharField(help_text='Veuillez saisir votre nom complet', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.TextField(help_text="Entrer le contenu de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='miniature',
            field=models.ImageField(help_text='Charger une image miniature', upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='resume',
            field=models.TextField(help_text="Entrer la resumé de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(help_text="Entrer le titre de l'article", max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, help_text='Veuillez saisir votre adresse email', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(help_text='Veuillez saisir votre message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nom',
            field=models.CharField(help_text='Veuillez saisir votre prénom', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='prenom',
            field=models.CharField(help_text='Veuillez saisir votre nom', max_length=100),
        ),
    ]
